# EpiBERT Training Configuration Example
# Copy and modify this file for your training runs

# Data paths
data:
  train_data: "data/processed/train"
  valid_data: "data/processed/valid"
  test_data: "data/processed/test"
  
# Model configuration
model:
  type: "pretraining"  # or "finetuning"
  input_length: 524288
  output_length: 4096
  final_output_length: 4092
  
# Training parameters
training:
  batch_size: 4
  learning_rate: 0.0001
  max_epochs: 100
  patience: 10
  
# Logging
logging:
  wandb_project: "epibert"
  wandb_entity: "your_username"
  log_dir: "logs"
  
# Hardware
hardware:
  num_gpus: 1
  num_workers: 4
  precision: "bf16"
